services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      DB_CONNECTION: sqlsrv
      DB_HOST: sqlserver  # Nombre del servicio de SQL Server
      DB_PORT: 1433
      DB_DATABASE: nombre_de_tu_base
      DB_USERNAME: sa
      DB_PASSWORD: TuPasswordSegura123!
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=TuPasswordSegura123!
    ports:
      - "1433:1433"

